### ISSUE TITLE
Error displaying task list in openEquella portal module

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA-blackboard-integration#12]
The EQUELLA Home, Search EQUELLA and Contribute to EQUELLA links all work fine, but the moderations task list part errors
![Capture](https://user-images.githubusercontent.com/4625498/54653398-acaaa280-4b0e-11e9-952e-58a49e65cff7.PNG)

**Comment by cbeach47** [comment]
@mrblippy - I can't replicate on the following setup.  What version of Bb, oE, and the B2/WS is failing for you?  Can you see if Bb or oE is offering any log messages of the error?

Bb:  3600.0.0-rel.6
oE:  6.5
B2/WS:  2.0.2

**Comment by mrblippy** [comment]
Sorry Chris, only just saw this. Will get you that info shortly

**Comment by mrblippy** [comment]
I found the actual error in the blackboard logs. Turns out my blackboard vm just had an issue(unknown host exception) contacting the equella instance i was using.

Once that was cleared up the task list is displaying
