### ISSUE TITLE
Change references from EQUELLA to openEQUELLA in the portal module

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA-blackboard-integration#13]
![Capture](https://user-images.githubusercontent.com/4625498/54653592-50944e00-4b0f-11e9-863f-e810fc293d4a.PNG)

The three links should now say 'openEQUELLA Home', 'Search openEQUELLA' and 'Contribute to openEQUELLA'

**Comment by cbeach47** [comment]
Fix merged into master.

**Comment by mrblippy** [comment]
Verified in master
