### ISSUE TITLE
Increase the Bb API version from v3400

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA-blackboard-integration#17]
For the API version to build the B2/WS against, we need to decide if we should bump up the version to v3500 (currently we build against v3400).  I have tested the v3400 API version in v3200, v3500, and v3600 without issue.

Things to consider:
- Can we make it work to only need one version of the B2/WS to support v3200 - v3600+ Bb integrations.
- Is it best practice (or recommended) to build with the Bb version that matches your target Bb install version?
- The benefit to building against the v3500 API version instead of the v3400 API
- Adverse effects that could occur in building against the v3500 API version, and then running the B2/WS on a v3200 install

**Comment by muthukrishnank** [comment]
**Can we make it work to only need one version of the B2/WS to support v3200 - v3600+ Bb integrations.**
		- Yes, we can maintain the same version of the B2/WS against different learn environments provided it is tested and working as expected
    **Is it best practice (or recommended) to build with the Bb version that matches your target Bb install version?**
		- Yes, it is a best practice to build the B2/WS against the specific versions of learn API
    **The benefit to building against the v3500 API version instead of the v3400 API**
		- This would make sure the B2/Ws doesn't use deprecated API's, also the functionality should work as expected
    **Adverse effects that could occur in building against the v3500 API version, and then running the B2/WS on a v3200 install**
		- There is a high possibilities that the BB API's may not be supported in the lower versions of Learn. Also some API's from 3200 might have been deprecated in 3500

**Comment by cbeach47** [comment]
Thanks @muthukrishnank - sounds like we should have the standard release match the latest major version of Bb SaaS as per https://bbprepo.blackboard.com/content/repositories/releases/blackboard/platform/bb-platform/ .

And while not inappropriate for adopters to use a B2/WS that has a different API version, a thorough test suite should be performed.

**Comment by cbeach47** [comment]
As a follow up, I've submitted https://github.com/equella/equella-blackboard-integration/issues/18
