### ISSUE TITLE
After editing oEQ content inside BB, returned to frames view

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA-blackboard-integration#8]
After editing the title of oEQ content added to BB via the B2,  I am returned to a slightly different view of the course (like an old UI or something that still uses frames).

Before editing content:
![bbstart](https://user-images.githubusercontent.com/1694589/53217760-731c7e00-36ad-11e9-9bd3-2f7fc62833e8.png)

After editing content:
![bbfin](https://user-images.githubusercontent.com/1694589/53217759-7283e780-36ad-11e9-8c3f-c67e059fcc71.png)

This seems to "stick".  Ie. navigating away from the course and then back into it will still show the UI from the second screenshot.  Only logging out and back in will restor the original UI.

**Comment by cbeach47** [comment]
I can't replicate this on Firefox today, but I can on Chrome on Bb SaaS 3500.11.0-rel.10+071f567

**Comment by cbeach47** [comment]
Found out that if 'open in new window' is set to 'Yes', this issue occurs.  When that flag is set, the `modify_proc.jsp` page includes `target="_blank"` in the `<a>` tag.  Not sure yet why that messes with the left-hand nav.

**Comment by mrblippy** [comment]
Verified in master
